## Convolutional graphs
###### Using np to realize backward propagation in convolutional network

In [2]:
import numpy as np

##### Testing summing up operations

In [3]:
np.random.seed(0)

In [7]:
H = 4
W = 3

In [15]:
x = np.random.randn(H,W)
y = np.random.randn(H,W)
z = np.random.randn(H,W)
print(x,'\n',y,'\n',z)

[[ 1.86755896  0.90604466 -0.86122569]
 [ 1.91006495 -0.26800337  0.8024564 ]
 [ 0.94725197 -0.15501009  0.61407937]
 [ 0.92220667  0.37642553 -1.09940079]] 
 [[ 0.29823817  1.3263859  -0.69456786]
 [-0.14963454 -0.43515355  1.84926373]
 [ 0.67229476  0.40746184 -0.76991607]
 [ 0.53924919 -0.67433266  0.03183056]] 
 [[-0.63584608  0.67643329  0.57659082]
 [-0.20829876  0.39600671 -1.09306151]
 [-1.49125759  0.4393917   0.1666735 ]
 [ 0.63503144  2.38314477  0.94447949]]


In [25]:
a = x * y
b = a + z
print(a,'\n',b)

[[ 0.55697737  1.20176486  0.59817968]
 [-0.28581169  0.11662262  1.48395351]
 [ 0.63683253 -0.0631607  -0.47278958]
 [ 0.4972992  -0.25383603 -0.03499454]] 
 [[-0.0788687   1.87819815  1.1747705 ]
 [-0.49411045  0.51262933  0.390892  ]
 [-0.85442506  0.376231   -0.30611608]
 [ 1.13233064  2.12930874  0.90948495]]


In [26]:
c = np.sum(b)
print(c)

6.77032501711


###### Using back path to compute derivatives

In [22]:
grad_c = 1.
grad_b = grad_c * np.ones((H,W))
grad_a = grad_b.copy()
print(grad_c)
print(grad_b)
print(grad_a)

1.0
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [27]:
grad_z = grad_b.copy()
grad_x = grad_a*y
grad_y = grad_a*x
print(grad_z)
print(grad_y)
print(grad_x)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.86755896  0.90604466 -0.86122569]
 [ 1.91006495 -0.26800337  0.8024564 ]
 [ 0.94725197 -0.15501009  0.61407937]
 [ 0.92220667  0.37642553 -1.09940079]]
[[ 0.29823817  1.3263859  -0.69456786]
 [-0.14963454 -0.43515355  1.84926373]
 [ 0.67229476  0.40746184 -0.76991607]
 [ 0.53924919 -0.67433266  0.03183056]]


###### The disadvantage of numpy is that (1) it cannot be used in GPU; (2) have to compute our own gradients one by one